// Generated by Selenium IDE

using System.Collections.Generic;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;

namespace InsuranceSolver
{
    [TestFixture]
    public class InsuranceSolver
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;

        [SetUp]
        public void SetUp()
        {
            driver = new FirefoxDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }

        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }

        [Test]
        public void InsuranceSolver_25and3and0_2500()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(889, 906);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Navjot");
            driver.FindElement(By.Id("lastName")).SendKeys("Singh");
            driver.FindElement(By.Id("address")).SendKeys("201 Lester St");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 3W3");
            driver.FindElement(By.Id("phone")).SendKeys("647-937-4862");
            driver.FindElement(By.Id("email")).SendKeys("epicnav@icloud.com");
            driver.FindElement(By.Id("age")).SendKeys("25");
            driver.FindElement(By.Id("experience")).SendKeys("3");
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("$2500"));
            }
        }
        
        [Test]
        public void InsuranceSolver_OmitFirstName_ValidationError()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(1179, 1038);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("Singh");
            driver.FindElement(By.Id("address")).SendKeys("201 Lester Street");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 3W3");
            driver.FindElement(By.Id("phone")).SendKeys("647-937-4862");
            driver.FindElement(By.Id("email")).SendKeys("epicnav@icloud.com");
            driver.FindElement(By.Id("age")).SendKeys("25");
            driver.FindElement(By.Id("experience")).SendKeys("3");
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            Assert.That(driver.FindElement(By.Id("firstName-error")).Text, Is.EqualTo("First Name is required"));
        }
        
        [Test]
        public void InsuranceSolver_OmitLastName_ValidationError()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(1179, 1038);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Navjot");
            driver.FindElement(By.Id("address")).SendKeys("201 Lester St");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 3W3");
            driver.FindElement(By.Id("phone")).SendKeys("647-937-4862");
            driver.FindElement(By.Id("email")).SendKeys("epicnav@icloud.com");
            driver.FindElement(By.Id("age")).SendKeys("26");
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("experience")).SendKeys("3");
            driver.FindElement(By.Id("btnSubmit")).Click();
            Assert.That(driver.FindElement(By.Id("lastName-error")).Text, Is.EqualTo("Last Name is required"));
        }
        
        [Test]
        public void InsuranceSolver_InvalidPhoneNumber_ValidationError()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(889, 906);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Navjot");
            driver.FindElement(By.Id("lastName")).SendKeys("Singh");
            driver.FindElement(By.Id("address")).SendKeys("201 Lester St");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 3W3");
            driver.FindElement(By.Id("phone")).SendKeys("6479374862");
            driver.FindElement(By.Id("email")).SendKeys("epicnav@icloud.com");
            driver.FindElement(By.Id("age")).SendKeys("27");
            driver.FindElement(By.Id("experience")).SendKeys("3");
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
        }
        
        [Test]
        public void InsuranceSolver_InvalidEmail_ValidationError()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(889, 906);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Navjot");
            driver.FindElement(By.Id("lastName")).SendKeys("Singh");
            driver.FindElement(By.Id("address")).SendKeys("201 Lester St");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 3W3");
            driver.FindElement(By.Id("phone")).SendKeys("647-937-4862");
            driver.FindElement(By.Id("email")).SendKeys("epicnav");
            driver.FindElement(By.Id("age")).SendKeys("28");
            driver.FindElement(By.Id("experience")).SendKeys("3");
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
        }
        
        [Test]
        public void InsuranceSolver_InvalidPostalCode_ValidationError()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(889, 906);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Navjot");
            driver.FindElement(By.Id("lastName")).SendKeys("Singh");
            driver.FindElement(By.Id("address")).SendKeys("201 Lester St");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L3W3");
            driver.FindElement(By.Id("phone")).SendKeys("647-937-4862");
            driver.FindElement(By.Id("email")).SendKeys("epicnav@icloud.com");
            driver.FindElement(By.Id("age")).SendKeys("35");
            driver.FindElement(By.Id("experience")).SendKeys("17");
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
        }
        
        [Test]
        public void InsuranceSolver_OmitAge_ValidationError()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(889, 906);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Navjot");
            driver.FindElement(By.Id("lastName")).SendKeys("Singh");
            driver.FindElement(By.Id("address")).SendKeys("201 Lester St");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L3W3");
            driver.FindElement(By.Id("phone")).SendKeys("647-937-4862");
            driver.FindElement(By.Id("email")).SendKeys("epicnav@icloud.com");
            driver.FindElement(By.Id("experience")).SendKeys("5");
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
        }
        
        [Test]
        public void InsuranceSolver_OmitAtFaultAccidents_ValidationError()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(889, 906);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Navjot");
            driver.FindElement(By.Id("lastName")).SendKeys("Singh");
            driver.FindElement(By.Id("address")).SendKeys("201 Lester St");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L3W3");
            driver.FindElement(By.Id("phone")).SendKeys("647-937-4862");
            driver.FindElement(By.Id("email")).SendKeys("epicnav@icloud.com");
            driver.FindElement(By.Id("age")).SendKeys("37");
            driver.FindElement(By.Id("experience")).SendKeys("8");
            driver.FindElement(By.Id("btnSubmit")).Click();
            Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
        }
        
        [Test]
        public void InsuranceSolver_OmitDrivingExperience_ValidationError()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(889, 906);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Navjot");
            driver.FindElement(By.Id("lastName")).SendKeys("Singh");
            driver.FindElement(By.Id("address")).SendKeys("201 Lester St");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 3W3");
            driver.FindElement(By.Id("phone")).SendKeys("647-937-4862");
            driver.FindElement(By.Id("email")).SendKeys("epicnav@icloud.com");
            driver.FindElement(By.Id("age")).SendKeys("45");
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
        }
        
        [Test]
        public void InsuranceSolver_45and5and4_InsuranceDeclined()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(889, 906);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Navjot");
            driver.FindElement(By.Id("lastName")).SendKeys("Singh");
            driver.FindElement(By.Id("address")).SendKeys("201 Lester St");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 3W3");
            driver.FindElement(By.Id("phone")).SendKeys("647-937-4862");
            driver.FindElement(By.Id("email")).SendKeys("epicnav@icloud.com");
            driver.FindElement(By.Id("age")).SendKeys("45");
            driver.FindElement(By.Id("experience")).SendKeys("5");
            driver.FindElement(By.Id("accidents")).SendKeys("4");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
            }
        }
        
        [Test]
        public void InsuranceSolver_45and12and0_1350()
        {
            driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
            driver.Manage().Window.Size = new System.Drawing.Size(889, 906);
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Navjot");
            driver.FindElement(By.Id("lastName")).SendKeys("Singh");
            driver.FindElement(By.Id("address")).SendKeys("201 Lester St");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 3W3");
            driver.FindElement(By.Id("phone")).SendKeys("647-937-4862");
            driver.FindElement(By.Id("email")).SendKeys("epicnav@icloud.com");
            driver.FindElement(By.Id("age")).SendKeys("45");
            driver.FindElement(By.Id("experience")).SendKeys("12");
            driver.FindElement(By.Id("accidents")).SendKeys("0");
            driver.FindElement(By.Id("btnSubmit")).Click();
            {
                string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("$1350"));
            }
        }
    }
}